// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend_fullstack_course.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251003181802_HorseModelModif2")]
    partial class HorseModelModif2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameModel.Fear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Discovered")
                        .HasColumnType("boolean");

                    b.Property<int>("FearType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HorseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.ToTable("Fear");
                });

            modelBuilder.Entity("GameModel.Horse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Breed")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("GameModel.PersonalityTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Discovered")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("HorseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.ToTable("PersonalityTrait");
                });

            modelBuilder.Entity("GameModel.Fear", b =>
                {
                    b.HasOne("GameModel.Horse", null)
                        .WithMany("Fears")
                        .HasForeignKey("HorseId");
                });

            modelBuilder.Entity("GameModel.PersonalityTrait", b =>
                {
                    b.HasOne("GameModel.Horse", null)
                        .WithMany("Personality")
                        .HasForeignKey("HorseId");
                });

            modelBuilder.Entity("GameModel.Horse", b =>
                {
                    b.Navigation("Fears");

                    b.Navigation("Personality");
                });
#pragma warning restore 612, 618
        }
    }
}
